### ISSUE TITLE
Hacer Diagrama de Caso de Uso

### ISSUE THREAD

**Issue by EmilianoBlazco** [streamhy/Tp4-Grupo_7#2]
Realizar diagrama de Caso de Uso para tener un manejo mas visual del entorno en el cual se esta trabajando y ver las tareas que realiza cada actor en el sistema

**Comment by streamhy** [comment]
- [ ] Obtener los actores
- [ ] Indicar los Casos de Uso por Actor
- [ ] Insertar el Diagrama de Caso de Uso

**Comment by EmilianoBlazco** [comment]
- [x]  Obtener los actores
- [x] Indicar los Casos de Uso por Actor
- [x] Insertar el Diagrama de Caso de Uso
